# project information
site_name: OpenSiv3D for Web docs
docs_dir: docs
site_dir: _site/docs
site_url: https://siv3d.kamenokosoft.com/docs

# theme
theme: 
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - English: 
    - en/index.md
    - Download:
      - en/download/web-vs.md
      - en/download/web-vscode-windows.md
      - Start Siv3D for Web Programming with macOS + Visual Studio Code: en/download/web-vscode-unix.md
      - Start Siv3D for Web Programming with Ubuntu + Visual Studio Code: en/download/web-vscode-unix.md
    - Publishing:
      - en/publishing/publishing.md
    - Reference:
      - en/reference/trouble-shooting.md
      - en/reference/web-specific-functions.md
      - en/reference/web-specific-notes.md
    - Experimental Feature:
      - en/experimental/using-threads.md
    - Join Development:
      - en/develop/build-siv3d-web.md
      - en/develop/build-user-guide.md
  - 日本語: 
    - ja/index.md
    - ダウンロード:
      - ja/download/web-vs.md
      - ja/download/web-vscode-windows.md
      - macOS + Visual Studio Code で Siv3D for Web プログラミングを始める: ja/download/web-vscode-unix.md
      - Ubuntu + Visual Studio Code で Siv3D for Web プログラミングを始める: ja/download/web-vscode-unix.md
    - WebGL アプリの公開:
      - ja/publishing/publishing.md
    - リファレンス:
      - ja/reference/trouble-shooting.md
      - ja/reference/web-specific-functions.md
      - ja/reference/web-specific-notes.md
    - 試験的機能:
      - ja/experimental/using-threads.md
    - 開発に参加する:
      - ja/develop/build-siv3d-web.md
      - ja/develop/build-user-guide.md
