name: Document e2e Test

on:
  push:
    branches: [ master ]

jobs:
  document-test:
    runs-on: windows-latest
    env:
      MSBuild_path: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\bin"
      VSIXInstaller_Path: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE"
      DevEnv_Path: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\Common7\\IDE\\devenv.exe"
      WinAppDriver_Path: "C:\\Program Files (x86)\\Windows Application Driver\\WinAppDriver.exe"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Test Runner
        working-directory: test/en
        run: |
          Set-Item Env:Path "$env:MSBuild_Path;$env:Path"
          nuget restore TestRunner.sln
          msbuild TestRunner.sln /p:Configuration="Release"

      - name: Start WinAppDriver
        run: Start-Process -FilePath "$env:WinAppDriver_Path" -ArgumentList "127.0.0.1","34723"

      - name: Install Emscripten
        working-directory: test/en
        run: |
          curl -L https://github.com/nokotan/EmscriptenInstaller/releases/download/v0.1.2/EmscriptenOffline.exe -o Emscripten.exe
          & ".\Emscripten.exe" /SILENT /SUPPRESSMSGBOXES
          Wait-Process -Name "Emscripten"
          $env:EMSDK = [System.Environment]::GetEnvironmentVariable("EMSDK","User")
          echo "EMSDK=$env:EMSDK" >> $env:GITHUB_ENV
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          echo $env:Path >> $Env:GITHUB_PATH

      - name: Install VSIX
        working-directory: test/en
        run: |
          Set-Item Env:Path "$env:VSIXInstaller_Path;$env:Path"
          curl -L https://github.com/nokotan/VSExtForEmscripten/releases/download/v0.7.0/Emscripten.Build.Definition.vsix -o Emscripten.vsix
          VSIXInstaller /quiet /admin Emscripten.vsix 
          Wait-Process -Name "VSIXInstaller"

      - name: Install Siv3D
        working-directory: test/en
        run: |
          Set-Item Env:Path "$env:VSIXInstaller_Path;$env:Path"
          curl -L https://github.com/nokotan/OpenSiv3D/releases/download/v0.6.6r3/OpenSiv3D-Installer-wasm.exe -o "OpenSiv3D(0.6.6)Web.exe"
          & ".\OpenSiv3D(0.6.6)Web.exe" /SILENT /SUPPRESSMSGBOXES /LOG="InstallLog.Log"
          Wait-Process -Name "OpenSiv3D(0.6.6)Web"
          cat InstallLog.Log
          $env:SIV3D_0_6_6_WEB = [System.Environment]::GetEnvironmentVariable("SIV3D_0_6_6_WEB","User")
          echo "SIV3D_0_6_6_WEB=$env:SIV3D_0_6_6_WEB" >> $env:GITHUB_ENV
          devenv /installvstemplates

      - name: Create Project
        working-directory: test/en
        continue-on-error: true
        run: |
          Start-Process -FilePath "$env:DevEnv_Path"
          & ".\running-code-with-visualstudio\bin\Release\RunningCodeWithVisualStudio.exe"
          Get-Process | Where-Object -FilterScript {$_.Name -eq "devenv"}  | Stop-Process

      - name: Save Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: ScreenShots
          path: test/en/*.png

      - name: Clean-up Process
        run: |
          Get-Process | Where-Object -FilterScript {$_.Name -eq "WinAppDriver"}  | Stop-Process
